### ISSUE TITLE
Desktop Notifications for New Tweets

### ISSUE THREAD

**Issue by DanHerbert** [cezarsa/silver_bird#108]
Chrome enabled desktop notifications in the dev channel a few weeks ago. It would be nice to see optional support added to notify new tweets using this.

http://www.chromium.org/developers/design-documents/desktop-notifications/api-specification
http://sandbox.gtaero.net/chrome/notifications.php

**Comment by cezarsa** [comment]
Hi Dan, I have started to work on desktop notifications some time ago and there's already a initial support in the current version but it's kinda hidden (You got to manually edit the options local storage entry and set "use_desktop_notifications":true).

I haven't added an option to the options page yet because I still need to deal with some formatting issues, I'll make sure to work on this for the next version.
Thanks.

**Comment by cezarsa** [comment]
Improved support for desktop notifications and adding an option to enable it. Closed by abd3e52e0832e90ca8e70b1a335c46840ec292f2.
