### ISSUE TITLE
Saying Message Not Sent When It Really Was

### ISSUE THREAD

**Issue by elijahmanor** [cezarsa/silver_bird#132]
The last week or so I've been getting many errors from Chromed Bird after I send a tweet.

It will say it is not successful, but when I go manually pull up my timeline (http://twitter.com/elijahmanor) I see that that tweet was sent.

When the error comes up I don't know if it really has sent or not... so I always double check so that I'm not trying to double-tweet.

It seems to happen maybe every other time. A friend of mine (who sits next to me at work) has experienced the same behavior.

**Comment by elijahmanor** [comment]
Here is a screenshot of the error... which keeps happening. Several times today already http://twitpic.com/1lsd3c

**Comment by dmohl** [comment]
I am experiencing the same problem.

**Comment by stevenrigney** [comment]
I've also been getting this error.

**Comment by cezarsa** [comment]
I'm on it now, that's really annoying.

**Comment by cezarsa** [comment]
So guys, commmits 7fda5f31600b097fb109 and b5018803b0edf34a0587 try to address this issue. Would you mind giving it a try and then letting me know if it helps with the problem?

**Comment by elijahmanor** [comment]
Sure, I'll pull down the master & test it...

**Comment by elijahmanor** [comment]
I think I liked it better when the composed stayed open until the message was sent. Looks like you changed it to close the compose immediately. Was that intentional?

**Comment by elijahmanor** [comment]
Ahh I just realized you probably did that so you could possibly queue up multiple messages. Is that correct? If so, that is cool ;)

**Comment by elijahmanor** [comment]
So far so good... I haven't see any issues when sending tweets

**Comment by cezarsa** [comment]
Nice! Good to hear that. You're right about queueing messages. There's no point in blocking user experience anymore since now we can correctly handle multiple message and deliver then in FIFO order. (Also blocking the user interface was a rather weak and error prone implementation since you could simply close the popup and open it again and then the UI would be unblocked.)
Queueing messages was also essential to deal with this problem. The real issue was Twitter taking too long in answering our requests and causing us to issue a client side timeout error. Now status update requests have a very long client side timeout value, and we will keep trying to send it until the request is successful. It'd be awful to block users for all this time.
I don't know if you've noticed, but after sending a tweet you can now hover the progress indicator icon and it will show you pending status updates and even let you cancel them if they are taking too long.
