### ISSUE TITLE
Duplicate tweet posts?

### ISSUE THREAD

**Issue by thnk2wn** [cezarsa/silver_bird#204]
A post I made from Chromed bird earlier today got published over and over again. I only hit the button to tweet once. I also noticed that it appeared to get an update today as the layout got whacky for a bit.  See  http://i17.photobucket.com/albums/b96/snowyangel1372/one.jpg

**Comment by cezarsa** [comment]
I'm really sorry for that. There were a few glitches with Twitter's API today that apparently caused Chromed Bird to re-send tweets while thinking they weren't previously successfully sent because the HTTP connection timed out and we never received a confirmation from Twitter.

The funny thing is that Twitter itself wasn't supposed to accept duplicated tweets, the /status/update page [1] explicitly says "A status update with text identical to the authenticating user's text identical to the authenticating user's current status will be ignored to prevent duplicates." and obviously this safety check was somehow bypassed.

Anyway, I need to find a way to better handle these situations and prevent twitter's insanity to bring chaos to Chromed Bird users. I'm really sorry for that and I'll take a look at it right now.

[1] - http://dev.twitter.com/doc/post/statuses/update

**Comment by thnk2wn** [comment]
That's okay and thanks for the info and looking into.

**Comment by cezarsa** [comment]
Improving the way we handle failed status updates, not perfect just a little better. Closed by 6ccc8e3364e025507ebfde0c21daec45a0f169e2
