### ISSUE TITLE
clicking on "x more tweet(s) available. Update now." doesn't do anything.

### ISSUE THREAD

**Issue by AD7six** [cezarsa/silver_bird#220]
As of recently, clicking on the notice that there are more tweets doesn't do anything - clicking "refresh" does.

On Arch linux using chrome 5.0.375.70

**Comment by jyy** [comment]
also experiencing the same problem.
win7 - chrome 7.0.517.44
ubuntu 9.04 - chrome 8.0.552.28 beta

**Comment by cezarsa** [comment]
I'm still not sure about what exactly is causing this behavior as I wasn't able to reproduce it. Does this happen consistently to you guys? Also does the "update now" bar always show even if you are at the top of the timeline or in these cases the timeline is correctly updated?

**Comment by jyy** [comment]
this has happened consistently since last thursday.  the "update now" does show with the correct number of new tweets, however clicking on it does not refresh the timeline.  after clicking on "update now," it goes away as if it is going to show more tweets, but then the "update now" simply pops back in.

one thing i just tried is to switch from the unified tab to the home tab, and that in effect refreshed my tweets.  The "update now" disappeared and the icon badge unread count gone as well, so i guess that will be my workaround for now.

**Comment by cezarsa** [comment]
I've just pushed some fixes to this bug. Would you mind testing the latest source[1] to see if this issue still happens?

[1] - Download https://github.com/cezarsa/chromed_bird/zipball/master and install it as an unpacked extension.

**Comment by jyy** [comment]
nice.. seems like the problem has been fixed... just got the "update now" to pop-up, then clicking on it refreshed my feed.  i'll install the unpacked extension on my computers at work tomorrow and will most likely confirm if the issue i was seeing is actually fixed.

**Comment by AD7six** [comment]
Fixed for me :)
