### ISSUE TITLE
Support third party Twitter API

### ISSUE THREAD

**Issue by danielfree** [cezarsa/silver_bird#29]
It will be great to have an option(or some hack) to set a different Twitter API address, which is quite useful for users from where twitter.com is blocked by firewall ( i.e. China ).

**Comment by cezarsa** [comment]
Some advanced options including overriding API's endpoint. Closed by 108cbae63e22f8ee2fad87deed23227c4e29528d

**Comment by spitfire2** [comment]
Many third party API only support Basic Auth,but Chromed Bird required OAuth. Please support Basic Auth.

**Comment by cezarsa** [comment]
I really don't like the idea of using Basic Auth, not only because of the fact that Chromed Bird will have access to user's password, but mainly because we'd have to store it in an unsafe storage (localStorage), and that's BAD(tm).
But not everything is lost, according to one of Twitter's developers [1], they're going to implement a way in which one can get OAuth's access token given user's name and password, so, from a user's point of view, the application would behave just like if it were using Basic Auth, but storing only the access token and not the plain text password.
I guess I'll wait until this new API is ready instead of using Basic Auth, it probably shouldn't take too long.

[1] - http://groups.google.com/group/twitter-development-talk/msg/18b38db599f6ad98

**Comment by spitfire2** [comment]
Thanks!! Hope Twitter team quickly implement the new api.

**Comment by cezarsa** [comment]
BTW, during my tests I was able to access (and authenticate using OAuth) using the birdnest proxy (http://nest.onedd.net/). The authentication using OAuth was a bit hacky because I needed to tweak with the < form action"" > field in the proxied authentication page, but in the end it worked. I think I'll write a wiki page about how one can do the same.

**Comment by cytown** [comment]
Great, I'll check the wiki later.

**Comment by cnhacktnt** [comment]
Hi,

Could you please don't abandon BasicAuth? because as you know, twitter has been blocked in china, our chinese users are using twitter via 3rd party API proxies.
Since twitter has stopped BasicAuth support, we developped new API proxies which could transform BasicAuth to OAuth requests, it works like this:

User <--BasicAuth--> API Proxy <--OAuth--> Twitter
(User can't access twitter directly, while the API Proxy can)

The API Proxy need to get the OAuth token for the user and store it first, this requires the user input his username and password for API Proxy to simulate browser requests to get User's OAuth token, in the meanwhile, it will store the md5_sum(combine with other salts) of the user's username/password information for authentication for the Proxy itself.

Yes, this could explose the user's username/password, but if the user don't trust the Proxy, he can temporarily change his username/password, bind his OAuth token on the 3rd Party API Proxy, then change his username/password back on twitter, after that, he can use the temporary authentication information in his twitter client software to access the API Proxy, but that requires the user to have a SSH Tunnel/VPN...etc, to access twitter first.

The most important point is, most API Proxies are private proxies just for users themselves or their friends, they don't have a trust problem.

So, could you consider to keep Basic Auth in your great ChromeBird?

Thanks!
