### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by GAZ082** [cezarsa/silver_bird#35]
Hi! I'm getting that error when trying to install. Linux, Ubuntu 9.10 64bit, Chromium 4.0.270.0 (34426). I could install and use the plugin a week ago, but now something seems broken.

**Comment by cezarsa** [comment]
I think this problem is due to incorrect date and time settings in your system. This usually causes OAuth authentication to fail. Please, check the FAQ: http://wiki.github.com/cezarsa/chromed_bird/faq

I'm closing this issue for now. If you think that's not the problem, could you please provide a full error message?
