### ISSUE TITLE
No Japanese support

### ISSUE THREAD

**Issue by keithfancher** [cezarsa/silver_bird#83]
Japanese text is displayed as boxes. The browser itself shows Japanese characters correctly, so it's probably not a config issue.

**Comment by edwardyoon** [comment]
Hi, 
I have some japanese friends such as http://twitter.com/Tetsuya_K
But, I don't see any problem, It seems work well.

**Comment by keithfancher** [comment]
Strange. This is likely a Chromium issue rather than a Chromed Bird issue, since no other extensions can seem to display Japanese text properly either. It displays fine in the browser itself, and I have the appropriate languages installed... hmmm.

**Comment by keithfancher** [comment]
I do. I've tested it and had the same problem on Arch Linux and Ubuntu 9.10. I've just tried it on Windows 7 (same settings, etc.) and everything displays properly.

I have Asian fonts installed, and every other app lets me display and input Japanese just fine. What really confuses me is the way Chromium renders Japanese pages properly -- it's only the extensions that can't seem to display the text.

Do you have any insight as to how extensions render things differently? Is there a particular font it's trying to use or something?

**Comment by cezarsa** [comment]
Hey there, thanks a lot for investigating this further.
So, there's a possiblity that Chromed Bird is the one to blame. Currently I don't have a linux box available because I'm traveling, but maybe you could make one little test.

In css/base.css I set body's font-family to "font-family: Helvetica, Arial, sans-serif;"
Could you try installing Chromed Bird as an unpacked extension (downloading http://github.com/cezarsa/chromed_bird/zipball/master) and changing css/base.css removing font-family line?
If you do this Chromed Bird will use Chrome's default font and then we'll know if that's the problem.
Thanks a lot.

**Comment by keithfancher** [comment]
Didn't seem to have any effect, unfortunately. I can try messing with the CSS, see if I can come up with anything.

**Comment by ghost** [comment]
I have the same problem, but my case is Hangul, Korean alphabet. I'm using ubuntu 9.10 and chrome 4.0.249.43. This problem may be caused by font or css because I changed source code related to font in css and it doesn't fix the problem. Textarea always shows rectangles instead of Hangul. Anyway, I found that this problem occurs in only textarea.

**Comment by keithfancher** [comment]
Updating to Chromium 5.0.307.5 seems to have solved this problem with all extensions!

**Comment by ghost** [comment]
@ktf-nsp I think so. After chrome is updated, the problem is disappeared. It might be caused by some bug of the old google chrome.

**Comment by cezarsa** [comment]
Cleaning up issues. Good to know it's working now.
